name: "Renderer"
description: "Turn dashboards into nice pictures"
version: "2.4.3"
slug: "renderer"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
webui: "http://[HOST]:[PORT:10000]/"
options:
  access_token: ""
  keep_browser_open: false
  home_assistant_url: "http://homeassistant:8123"
schema:
  access_token: str
  keep_browser_open: bool
  home_assistant_url: str
